services:
  maria:
    image: 'mariadb:latest'
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
networks:
  boiler_plate: # 추후 사용시 맞는 네트워크 명으로 변경권장
    driver: bridge